<?php

use Illuminate\Database\Seeder;

class ContentsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('contents')->insert([
        ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
         'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
         'like'=>4,
         'contents_package'=>46,
         'name'=>'경북궁'
       ],
//        ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//         'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//         'like'=>4,
//         'contents_package'=>2,
//         'name'=>'경북궁123'
//       ],
//       ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//        'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//        'like'=>4,
//        'contents_package'=>3,
//        'name'=>'경북궁4124'
//      ],
//      ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//       'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//       'like'=>4,
//       'contents_package'=>3,
//       'name'=>'경북궁676'
//     ],
//     ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//      'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//      'like'=>4,
//      'contents_package'=>8,
//      'name'=>'경북궁34'
//    ],
//    ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//     'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//     'like'=>4,
//     'contents_package'=>8,
//     'name'=>'경북궁124'
//   ],
//   ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//    'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//    'like'=>4,
//    'contents_package'=>7,
//    'name'=>'경북궁55'
//  ],
//  ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//   'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//   'like'=>4,
//   'contents_package'=>7,
//   'name'=>'경북궁15'
// ],
// ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//  'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//  'like'=>4,
//  'contents_package'=>8,
//  'name'=>'경북궁90'
// ],
// ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//  'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//  'like'=>4,
//  'contents_package'=>6,
//  'name'=>'경북궁1111'
// ],
// ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//  'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//  'like'=>4,
//  'contents_package'=>3,
//  'name'=>'경북궁45'
// ],
// ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//  'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//  'like'=>4,
//  'contents_package'=>2,
//  'name'=>'경북궁124'
// ],
// ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//  'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//  'like'=>4,
//  'contents_package'=>7,
//  'name'=>'경북궁90'
// ],
// ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//  'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//  'like'=>4,
//  'contents_package'=>3,
//  'name'=>'경북궁124'
// ],
// ['spec'=> '{  "type": "fqwfqw",  "vertical": "",  "horizontal": "",  "location": "",  "visionable": "TRUE",  "clickable": "TRUE",  "disable": "TRUE",  "packagenum": ""}',
//  'xml'=>'<xml xmlns="http://www.w3.org/1999/xhtml">  <block type="factory_base" id="3DgX8=#H=y6Z)n,e/FIr" deletable="false" movable="false" x="0" y="0">    <mutation connections="null"></mutation>    <field name="NAME">fqwfqw</field>    <value name="VERTICAL">      <block type="vertical" id="CFWzr8I(htgr44fS[][i" deletable="false" movable="false">        <field name="VERTICAL"></field>      </block>    </value>    <value name="HORIZONTAL">      <block type="horizontal" id="J8i1qShlx5c#!@oJz355" deletable="false" movable="false">        <field name="HORIZONTAL"></field>      </block>    </value>    <value name="VISIONABLE">      <block type="logic_boolean" id="r@Rq]=306eRV4wjzPMuE" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="CLICKABLE">      <block type="logic_boolean" id="xzVtAFCxq/^v9rH`hgv(" deletable="false" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="DISABLE">      <block type="logic_boolean" id="?hSw3`:,oMoueQB(8SX+" movable="false">        <field name="BOOL">TRUE</field>      </block>    </value>    <value name="PACKAGENUM">      <block type="packagenum" id="IeBLF@+$oW*)?d=yy~9g" deletable="false" movable="false">        <field name="PACKAGENUM"></field>      </block>    </value>  </block></xml>',
//  'like'=>4,
//  'contents_package'=>3,
//  'name'=>'경북궁3443'
// ]
        ]);
    }
}
